export const MENU_PRICES: Record<string, { name: string; price: number }> = {
  bawse:       { name: "Bawse Dawg",              price: 13 },
  dirty:       { name: "Dirty South Dawg",         price: 12 },
  elote:       { name: "Elote Dawg",               price: 12 },
  nash:        { name: "Nash Dawg",                price: 12 },
  nacho:       { name: "Nacho Dawg",               price: 11 },
  plain:       { name: "Plain Jane",               price:  9 },
  big:         { name: "Big Dawg",                 price: 11 },
  demi:        { name: "Demi Dawg",                price: 11 },
  walking:     { name: "Walking Dawg",             price:  9 },
  byo:         { name: "Base Dawg",                price: 10 },
  bawse_fries: { name: "Bawse Fries",              price: 10 },
  elote_fries: { name: "Elote Fries",              price:  9 },
  dirty_fries: { name: "Dirty Fries",              price:  9 },
  nacho_fries: { name: "Nacho Fries",              price:  9 },
  big_fries:   { name: "Big Fries",                price:  8 },
  chips:       { name: "Chips",                    price:  3 },
  fries:       { name: "Fries",                    price:  5 },
  elote_cup:   { name: "Elote Cup",                price:  5 },
  water:       { name: "Water",                    price:  3 },
  soda:        { name: "Soda",                     price:  4 },
  lemonade:    { name: "Lemonade",                 price:  5 },
  pie:         { name: "Mini Sweet Potato Pie",    price:  5 },
  brownie:     { name: "Brownie",                  price:  5 },
};
